Metadata-Version: 2.4
Name: dataflow_custom_extension
Version: 0.1.0rc1
Classifier: Framework :: Jupyter
Classifier: Framework :: Jupyter :: JupyterLab
Classifier: Framework :: Jupyter :: JupyterLab :: 4
Classifier: Framework :: Jupyter :: JupyterLab :: Extensions
Classifier: Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.9
Classifier: Programming Language :: Python :: 3.10
Classifier: Programming Language :: Python :: 3.11
Classifier: Programming Language :: Python :: 3.12
Classifier: Programming Language :: Python :: 3.13
Requires-Python: >=3.9
Description-Content-Type: text/markdown

# Dataflow Jupyter Extension

A JupyterLab extension for dataflow customizations


## Customizations

<details>
<summary>Added custom connection lost restart command</summary>

#### `dataflow-custom:hub-restart`
-   This command has been replaced for default `hub:restart` because of it's redirection to _/hub/spawn_ , which should not be the case. So now the it redirects to _/hub/ui_ in iframe , which will be handled by UI and "App is not running" message will be shown
- Modified the connectionLost dialog to use the `dataflow-custom:hub-restart` command

</details>

### Packaging the extension

See [RELEASE](RELEASE.md)
